<?php
$products = [
    [
        'id'=> 1,
        'name' => 'Croccantini',
        'imgPath' => 'https://www.ideashoppingcenter.it/files/archivio_Files/Foto/39147_2.JPG',
        'price'=> 0.99,
        'brand'=> 'pippo',
        'category'=> 'cat',
        'use'=> 'food',
    ],
    [
        'id'=> 2,
        'name' => 'Bastoncino per Denti',
        'imgPath' => 'https://static.zoomalia.com/prod_img/108783/lm_46098b297950041a42470269d56260243a11637858771.jpg',
        'price'=> 2.50,
        'brand'=> 'pippo',
        'category'=> 'cat',
        'use'=> 'food',
    ],
    [
        'id'=> 3,
        'name' => 'Topolino a batteria',
        'imgPath' => 'https://images.obi-italia.it/product/IT/412x329/167560_1.jpg',
        'price'=> 4.50,
        'brand'=> 'pippo',
        'category'=> 'cat',
        'use'=> 'toy',
    ],
    [
        'id'=> 4,
        'name' => 'Albero con piattaforme',
        'imgPath' => 'https://m.media-amazon.com/images/I/71BTFDd72UL._AC_SY355_.jpg',
        'price'=> 19.99,
        'brand'=> 'pippo',
        'category'=> 'cat',
        'use'=> 'bed',
    ],
    [
        'id'=> 5,
        'name' => 'Tiragraffi',
        'imgPath' => 'https://arcaplanet.vtexassets.com/arquivos/ids/262222/tiragraffi-north-pole-lovedi.png?v=1757207683',
        'price'=> 14.99,
        'brand'=> 'pippo',
        'category'=> 'cat',
        'use'=> 'toy',
    ],
    [
        'id'=> 6,
        'name' => 'Croccantini',
        'imgPath' => 'https://images.heb.com/is/image/HEBGrocery/002083057?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0',
        'price'=> 0.99,
        'brand'=> 'pippo',
        'category'=> 'dog',
        'use'=> 'food',
    ],
    [
        'id'=> 7,
        'name' => 'Bastoncino per Denti',
        'imgPath' => 'https://sementiecereali.compracomodo.it/Assets/Public/1/prodotti/Petfood/Mars/dentastix-56-small-new.jpg',
        'price'=> 2.50,
        'brand'=> 'pippo',
        'category'=> 'dog',
        'use'=> 'food',
    ],
    [
        'id'=> 8,
        'name' => 'Palla di Gomma',
        'imgPath' => 'https://www.canibo.it/wp-content/uploads/2018/10/pallina-retata-per-cani.jpg',
        'price'=> 4.50,
        'brand'=> 'pippo',
        'category'=> 'dog',
        'use'=> 'toy',
    ],
    [
        'id'=> 9,
        'name' => 'Cesto con cuscino',
        'imgPath' => 'https://www.clama.it/db/wp-content/uploads/2018/11/M8543.jpg',
        'price'=> 14.99,
        'brand'=> 'pippo',
        'category'=> 'dog',
        'use'=> 'bed',
    ],
    [
        'id'=> 10,
        'name' => 'Casetta in Legno',
        'imgPath' => 'https://images.eprice.it/nobrand/0/hres/516/207977516/8718475715283_a_en_hd_1.jpg',
        'price'=> 59.99,
        'brand'=> 'pippo',
        'category'=> 'dog',
        'use'=> 'bed',
    ],
    
];